#include <cstdint>
#pragma once


// ClientOrder is the order format sent by client to engine
struct ClientOrder 
{
    uint32_t price; // price in ticks
    uint16_t quantity; // self explanatory
    uint16_t orderID; // engine id assigned by gateway
    uint8_t type; // 0 for buy, 1 for sell, 2 for cancel, 3 for market buy, 4 for market sell
};

// EngineOrder is the order format stored in engine's order book
struct EngineOrder {
    uint16_t quantity; // self explanatory
    uint16_t orderID; // engine id assigned by gateway, same as ClientOrder's orderID
    uint8_t  levelNext; // index of the next order in the same price level array, 255 if it's the last order
    uint8_t  levelPrev; // index of the previous order in the same price level array, 255 if it's the first order
};

// GlobalOrderInfo is used in the direct lookup table to find the order's position in the price level array and its side (buy/sell)
struct GlobalOrderInfo
{
    uint16_t priceLevel; // index of the price level in the order book
    uint8_t posInArray; // index of the order in the price level array
    uint8_t side; // 0 for buy, 1 for sell
    bool live; // whether the order is still live (not fully filled or cancelled)
};

// Event is the format of events generated by the engine after processing an order, which will be sent back to the gateway
struct Event
{
    uint32_t price; // price in ticks for the event occuring
    uint16_t quantity; // quantity for the event occuring
    uint16_t orderID; // engine id for the order that triggered the event
    uint8_t type; // 0 for cancel, 1 for fill, 2 for acknowledgement
    uint8_t side; // 0 for buy (bid), 1 for sell (ask)
    bool fullyFilled; // whether the order is fufilled
    uint8_t padding[3]; // padding to align the struct to 16 bytes for better cache performance
};

// FillResult is a struct returned from PriceLevel, containing remaining order, and any produced events
struct FillResult
{
    ClientOrder remaining; // the remaining order after filling, with updated quantity
    Event events[64]; // events generated from the filling process, up to 64 events can be generated
    uint8_t eventCount; // amount of events generated
};

struct levelSummary
{
    uint32_t price;
    uint32_t qty;
};

struct BookSnapshot
{
    levelSummary bids[10];
    levelSummary asks[10];
    int bidCount;
    int askCount;
    uint64_t totalOrders;
};